"""
skill_factory_brain.py – The ninth brain. Gigia's skill creation engine.

Responsibilities
----------------
1. PATTERN DISCOVERY → COMPOSITION
   Tracks which skill sequences succeed repeatedly. When the same sequence
   wins N times, it composes them into a new single skill registered in almcp.

2. GAP DETECTION → CODE GENERATION
   Listens for SKILL_GAP_DETECTED events. When PlanningBrain can't find a
   suitable skill, this brain generates Python code for one, validates it,
   and stages it — ready to be used for the current goal without being
   globally visible yet.

   Lifecycle:  draft → staged → active → disabled

   draft   : code generated by LLM, stored in executor SQLite
   staged  : passed strict AST validation + local test run; usable for
             the current goal but NOT in the global almcp catalog
   active  : ran successfully in production with valid output; registered
             in almcp via POST /api/skills/generate; globally discoverable
   disabled: failed any validation, test, or runtime check

3. METADATA IMPROVEMENT
   Reads the full catalog from almcp and improves weak metadata (tags,
   descriptions, best_used_when) using real execution data.

almcp endpoints used
--------------------
  GET   /api/skills/catalog   — read global catalog
  POST  /api/skills/compose   — register composed skill
  PATCH /api/skills/improve   — update metadata on existing skill
  POST  /api/skills/generate  — register a code-generated skill (active)
"""

from __future__ import annotations

import asyncio
import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Callable, Coroutine, Dict, List, Optional, Set, Tuple

import aiohttp

from giga_ai.messaging.event_bus import EventBus, EventType
from giga_ai.memory.skill_memory import SkillMemory
from giga_ai.skills.executor import (
    create_draft,
    disable_skill,
    get_db_path,
    get_staged_metadata,
    get_skill_status,
    promote_to_active,
    validate_and_stage,
)
from giga_ai.utils.logger import get_logger

log = get_logger(__name__)

# ── Tunables ─────────────────────────────────────────────────────────────────
_COMPOSE_THRESHOLD  = 3
_MIN_SEQUENCE_LEN   = 2
_MAX_SEQUENCE_LEN   = 6
_IMPROVE_INTERVAL_S = 1800
_HTTP_TIMEOUT_S     = 15

# ── Composition prompts ───────────────────────────────────────────────────────

_COMPOSE_NAME_SYSTEM = """\
You name and describe new composed AI skills. A composed skill is a named pipeline
of existing skills that always runs together to accomplish a specific goal type.
Return ONLY valid JSON — no markdown, no extra text:
{"slug": "snake_case_name", "name": "Display Name", "description": "what it does in one sentence",
 "tags": ["tag1","tag2","tag3"], "best_used_when": "one sentence"}"""

# ── Metadata improvement prompt ───────────────────────────────────────────────

_IMPROVE_SYSTEM = """\
You improve AI skill catalog metadata. Given a skill's name and real usage data,
write better tags, description, and best_used_when.
Return ONLY valid JSON:
{"tags": ["tag1","tag2",...], "description": "...", "best_used_when": "..."}
Keep descriptions under 120 chars. Tags should be single lowercase words or short phrases."""

# ── Code generation prompt ────────────────────────────────────────────────────

_GENERATE_SYSTEM = """\
You are a skill generator for Gigia, an autonomous AI agent. Generate a Python skill module.

A skill is a Python module with exactly ONE function:
  def run(input_data: dict) -> dict

STRICT RULES — any violation means the skill will be rejected:
  FORBIDDEN imports: os, sys, subprocess, socket, pathlib, shutil, ctypes,
    importlib, pickle, glob, threading, multiprocessing, tempfile
  FORBIDDEN builtins: eval, exec, compile, __import__, open, globals, locals
  FORBIDDEN calls: os.system, os.environ, subprocess.Popen, subprocess.run,
    subprocess.call, os.popen, any dunder attribute not listed below
  ALLOWED dunders: __init__, __repr__, __str__, __len__, __iter__, __next__,
    __getitem__, __setitem__, __contains__, __enter__, __exit__

  ALLOWED standard library: json, re, datetime, math, collections, itertools,
    string, base64, hashlib, html, xml.etree.ElementTree, csv, io
  ALLOWED if network=true in metadata: requests, httpx

  Return {"error": "..."} on expected failures instead of raising
  Output must be a dict with JSON-serializable values (str/int/float/bool/list/dict/None)
  Under 80 lines

Respond with ONLY valid JSON (no markdown fences, no extra keys):
{
  "code": "...full Python source as a single string with \\n for newlines...",
  "slug": "snake_case_identifier",
  "name": "Display Name (3-6 words)",
  "description": "What it does (max 120 chars)",
  "tags": ["tag1", "tag2", "tag3"],
  "best_used_when": "One sentence describing when to use this skill",
  "input_schema": {
    "type": "object",
    "properties": {
      "field": {"type": "string", "description": "What this field is"}
    },
    "required": ["field"]
  },
  "output_schema": {
    "type": "object",
    "properties": {
      "result_field": {"type": "string", "description": "What this contains"}
    },
    "required": ["result_field"]
  },
  "credit_cost": 2,
  "allow_network": false
}"""

_GENERATE_USER_TEMPLATE = """\
A user tried to accomplish this goal but Gigia had no suitable skill for it:
  "{goal}"

Available candidates: {candidate_count} skills were found but none matched.

Design and generate a new Python skill that handles this type of goal.
Focus on the CAPABILITY GAP — make the skill reusable for similar goals, not just this one specific request.
The skill must work with zero API keys (pure computation, parsing, or public data only)."""


class SkillFactoryBrain:
    """
    Ninth brain — discovers successful skill patterns and registers them as
    new composed skills; generates Python code for capability gaps; improves
    metadata on existing skills.
    """

    def __init__(
        self,
        event_bus: EventBus,
        skill_memory: SkillMemory,
        llm_client: Any,
        gateway_url: str,
        giga_secret: str,
    ) -> None:
        self._bus          = event_bus
        self._skill_memory = skill_memory
        self._llm          = llm_client
        self._gateway_url  = gateway_url.rstrip("/")
        self._secret       = giga_secret

        # Composition tracking
        self._goal_sequences: Dict[str, List[str]] = {}
        self._sequence_counts: Dict[Tuple[str, ...], int] = defaultdict(int)
        self._composed: Set[Tuple[str, ...]] = set()

        # Improvement tracking
        self._improved: Set[str] = set()

        # Gap generation: slugs currently being generated (dedup)
        self._gaps_in_flight: Set[str] = set()

        # Staged slugs → goal_id, for promotion after successful execution
        self._staged_for_goal: Dict[str, str] = {}   # slug → goal_id

        self._skill_task:    Optional[asyncio.Task] = None
        self._complete_task: Optional[asyncio.Task] = None
        self._improve_task:  Optional[asyncio.Task] = None
        self._gap_task:      Optional[asyncio.Task] = None
        self._promote_task:  Optional[asyncio.Task] = None

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        self._skill_task    = asyncio.create_task(self._skill_listener(),    name="factory_skill")
        self._complete_task = asyncio.create_task(self._complete_listener(), name="factory_complete")
        self._improve_task  = asyncio.create_task(self._improve_loop(),      name="factory_improve")
        self._gap_task      = asyncio.create_task(self._gap_listener(),      name="factory_gap")
        self._promote_task  = asyncio.create_task(self._promote_listener(),  name="factory_promote")
        log.info("SkillFactoryBrain: started")

    async def stop(self) -> None:
        for t in [self._skill_task, self._complete_task, self._improve_task,
                  self._gap_task, self._promote_task]:
            if t and not t.done():
                t.cancel()
                try:
                    await t
                except asyncio.CancelledError:
                    pass
        log.info("SkillFactoryBrain: stopped")

    # ── Public API: called directly by PlanningBrain ──────────────────────────

    async def generate_and_stage(
        self,
        goal_desc: str,
        candidate_count: int,
    ) -> Optional[str]:
        """
        Generate a Python skill for the capability gap described by goal_desc,
        validate it, and stage it.

        Returns the slug if staging succeeded, None otherwise.
        This is called synchronously (with await) by PlanningBrain — it must
        complete within the caller's timeout (typically 90s).
        """
        db_path = get_db_path()
        if not db_path:
            log.warning("SkillFactoryBrain.generate_and_stage: db_path not set")
            return None

        dedup_key = goal_desc[:120].lower()
        if dedup_key in self._gaps_in_flight:
            log.info("SkillFactoryBrain: generation already in flight for similar gap")
            return None
        self._gaps_in_flight.add(dedup_key)

        try:
            slug = await self._generate_and_stage_internal(goal_desc, candidate_count, db_path)
            return slug
        finally:
            self._gaps_in_flight.discard(dedup_key)

    async def get_staged_metadata(self, slug: str) -> Optional[Dict[str, Any]]:
        """Return staged skill metadata for PlanningBrain to build a candidate."""
        db_path = get_db_path()
        if not db_path:
            return None
        return await get_staged_metadata(db_path, slug)

    # ── Gap generation (internal) ─────────────────────────────────────────────

    async def _generate_and_stage_internal(
        self,
        goal_desc: str,
        candidate_count: int,
        db_path: str,
    ) -> Optional[str]:
        log.info("SkillFactoryBrain: generating skill for gap",
                 extra={"goal": goal_desc[:80], "candidates": candidate_count})

        # 1. Ask LLM to generate code + metadata
        prompt = _GENERATE_USER_TEMPLATE.format(
            goal=goal_desc[:300],
            candidate_count=candidate_count,
        )
        try:
            raw = await self._llm.complete(prompt, system_prompt=_GENERATE_SYSTEM, json_mode=False)
            raw = _strip_fences(raw)
            meta = json.loads(raw)
        except Exception as exc:
            log.error("SkillFactoryBrain: LLM generation failed", extra={"e": str(exc)})
            return None

        slug = meta.get("slug", "")
        code = meta.get("code", "")

        if not slug or not code:
            log.warning("SkillFactoryBrain: LLM returned no slug or code")
            return None

        # Sanitise slug
        slug = re.sub(r"[^a-z0-9_]", "_", slug.lower())[:60]
        if not re.match(r'^[a-z]', slug):
            slug = "gen_" + slug

        log.info("SkillFactoryBrain: generated code", extra={"slug": slug, "lines": code.count('\n')})

        # 2. Store as draft
        try:
            await create_draft(
                db_path, slug, code,
                name=meta.get("name", slug.replace("_", " ").title()),
                description=meta.get("description", f"Generated for: {goal_desc[:80]}"),
                input_schema=meta.get("input_schema"),
                output_schema=meta.get("output_schema"),
                allow_network=bool(meta.get("allow_network", False)),
                created_by="skill_factory_brain",
            )
        except Exception as exc:
            log.error("SkillFactoryBrain: draft storage failed", extra={"e": str(exc)})
            return None

        # 3. Validate + stage (AST check → test run → output schema check)
        ok, msg = await validate_and_stage(db_path, slug)
        if not ok:
            log.warning("SkillFactoryBrain: staging failed",
                        extra={"slug": slug, "reason": msg})
            return None

        log.info("SkillFactoryBrain: skill staged successfully", extra={"slug": slug})
        return slug

    # ── Gap event listener (for async/background gap detection) ──────────────

    async def _gap_listener(self) -> None:
        """
        Background listener: handles SKILL_GAP_DETECTED events that arrive
        outside the PlanningBrain's direct generate_and_stage() call path
        (e.g. from non-skill-mode failures).
        """
        async for msg in self._bus.subscribe(EventType.SKILL_GAP_DETECTED):
            try:
                p = msg.payload
                goal_desc       = p.get("goal_description", "")
                candidate_count = p.get("candidate_count", 0)
                if not goal_desc:
                    continue
                # Only background-generate if PlanningBrain didn't already
                # await generate_and_stage() directly (dedup_key check handles this)
                asyncio.create_task(
                    self.generate_and_stage(goal_desc, candidate_count),
                    name="factory_generate_bg",
                )
            except Exception as exc:
                log.error("SkillFactoryBrain: gap_listener error", extra={"e": str(exc)})

    # ── Promote staged → active after successful production run ───────────────

    async def _promote_listener(self) -> None:
        """
        Listens for SKILL_EXECUTED events. When a staged skill ran successfully
        in production, promotes it to active and registers it in almcp.
        """
        async for msg in self._bus.subscribe(EventType.SKILL_EXECUTED):
            try:
                p = msg.payload
                slug    = p.get("slug", "")
                success = p.get("success", False)
                staged  = p.get("staged", False)

                if not (slug and success and staged):
                    continue

                db_path = get_db_path()
                if not db_path:
                    continue

                status = await get_skill_status(db_path, slug)
                if status != "staged":
                    continue

                log.info("SkillFactoryBrain: promoting staged skill to active",
                         extra={"slug": slug})
                await self._promote_to_catalog(db_path, slug)

            except Exception as exc:
                log.error("SkillFactoryBrain: promote_listener error", extra={"e": str(exc)})

    async def _promote_to_catalog(self, db_path: str, slug: str) -> None:
        """Promote staged → active locally, then register in almcp."""
        meta = await get_staged_metadata(db_path, slug)
        if not meta:
            return

        # Build almcp endpoint URL from the gateway URL
        gigiaBase = self._gateway_url  # this is actually almcp — we need the VPS URL
        # The VPS URL is not stored in SkillFactoryBrain config directly.
        # We construct it from the executor's local address (always same VPS).
        # almcp knows the VPS URL from GIGA_BRAIN_URL env var; we just pass
        # the slug and almcp constructs the full URL itself.

        # 1. Register in almcp (active=true)
        ok, resp = await self._post("/api/skills/generate", {
            "slug":           slug,
            "name":           meta.get("name", slug.replace("_", " ").title()),
            "description":    meta.get("description", f"Generated skill: {slug}"),
            "tags":           [],
            "input_schema":   meta.get("input_schema"),
            "credit_cost":    2,
            "created_by":     "skill_factory_brain",
            "generated_from": f"promoted from staged: {slug}",
        })

        if ok:
            now = datetime.now(timezone.utc).isoformat()
            await promote_to_active(
                db_path, slug,
                endpoint_url=f"registered:{resp.get('slug', slug)}",
            )
            log.info("SkillFactoryBrain: skill promoted to active and registered in almcp",
                     extra={"slug": slug, "credits": resp.get("credit_cost")})
        elif resp.get("error") == "slug_taken":
            # Already registered (race condition) — still mark active locally
            await promote_to_active(db_path, slug)
            log.info("SkillFactoryBrain: slug already in almcp — promoted locally",
                     extra={"slug": slug})
        else:
            log.warning("SkillFactoryBrain: almcp registration failed",
                        extra={"slug": slug, "resp": resp})

    # ── Pattern tracking (composition) ────────────────────────────────────────

    async def _skill_listener(self) -> None:
        async for msg in self._bus.subscribe(EventType.SKILL_EXECUTED):
            try:
                p = msg.payload
                goal_id = p.get("goal_id", "")
                slug    = p.get("slug", "")
                success = p.get("success", False)
                # Don't track staged runs in composition patterns
                if goal_id and slug and success and not p.get("staged", False):
                    if goal_id not in self._goal_sequences:
                        self._goal_sequences[goal_id] = []
                    if slug not in self._goal_sequences[goal_id]:
                        self._goal_sequences[goal_id].append(slug)
            except Exception:
                pass

    async def _complete_listener(self) -> None:
        async for msg in self._bus.subscribe(EventType.GOAL_COMPLETED):
            try:
                p = msg.payload
                goal_id     = p.get("goal_id", "")
                success     = p.get("success", False)
                goal_desc   = p.get("goal_description", "")
                sequence    = self._goal_sequences.pop(goal_id, [])

                if not success or len(sequence) < _MIN_SEQUENCE_LEN:
                    continue
                if len(sequence) > _MAX_SEQUENCE_LEN:
                    continue
                if "_self_improvement" in goal_desc.lower():
                    continue

                key = tuple(sequence)
                self._sequence_counts[key] += 1
                count = self._sequence_counts[key]

                log.info("SkillFactoryBrain: sequence recorded",
                         extra={"sequence": sequence, "count": count})

                if count >= _COMPOSE_THRESHOLD and key not in self._composed:
                    self._composed.add(key)
                    asyncio.create_task(
                        self._compose(list(key), goal_desc, count),
                        name=f"factory_compose_{key[0][:8]}",
                    )
            except Exception as exc:
                log.error("SkillFactoryBrain: complete_listener error", extra={"e": str(exc)})

    # ── Composition ───────────────────────────────────────────────────────────

    async def _compose(self, sequence: List[str], example_goal: str, success_count: int) -> None:
        log.info("SkillFactoryBrain: composing",
                 extra={"sequence": sequence, "count": success_count})

        prompt = (
            f"Skill sequence that succeeded {success_count} times: {' → '.join(sequence)}\n"
            f"Example goal it accomplished: '{example_goal[:200]}'\n\n"
            f"Name this composed skill pipeline."
        )
        try:
            raw  = await self._llm.complete(prompt, system_prompt=_COMPOSE_NAME_SYSTEM)
            raw  = _strip_fences(raw)
            meta = json.loads(raw)
        except Exception as exc:
            log.error("SkillFactoryBrain: naming failed", extra={"e": str(exc)})
            return

        slug = meta.get("slug", "")
        if not slug or not re.match(r'^[a-z0-9_]+$', slug):
            slug = "composed_" + "_".join(s.split("_")[0] for s in sequence[:3])

        workflow = []
        for i, skill in enumerate(sequence):
            step: Dict[str, str] = {"skill": skill}
            if i < len(sequence) - 1:
                step["output_as"] = f"step_{i}_{skill.split('_')[0]}"
            workflow.append(step)

        payload = {
            "slug":            slug,
            "name":            meta.get("name", slug.replace("_", " ").title()),
            "description":     meta.get("description", f"Composed: {' → '.join(sequence)}"),
            "tags":            meta.get("tags", []),
            "best_used_when":  meta.get("best_used_when", ""),
            "workflow":        workflow,
            "discovered_from": example_goal[:300],
            "success_count":   success_count,
        }

        ok, resp = await self._post("/api/skills/compose", payload)
        if ok:
            log.info("SkillFactoryBrain: composed skill registered",
                     extra={"slug": slug, "steps": len(sequence), "credits": resp.get("credit_cost")})
        elif resp.get("error") == "slug_taken":
            log.info("SkillFactoryBrain: composition already exists", extra={"slug": slug})
        else:
            log.warning("SkillFactoryBrain: compose failed", extra={"resp": resp})

    # ── Metadata improvement ──────────────────────────────────────────────────

    async def _improve_loop(self) -> None:
        await asyncio.sleep(300)
        while True:
            try:
                await self._run_improvement_cycle()
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                log.error("SkillFactoryBrain: improve_loop error", extra={"e": str(exc)})
            await asyncio.sleep(_IMPROVE_INTERVAL_S)

    async def _run_improvement_cycle(self) -> None:
        ok, data = await self._get("/api/skills/catalog")
        if not ok:
            return
        catalog  = data.get("skills", [])
        improved = 0

        for skill in catalog:
            slug = skill.get("slug", "")
            if slug in self._improved:
                continue
            tags = skill.get("tags") or []
            desc = skill.get("description") or ""
            buw  = skill.get("best_used_when") or ""
            needs = len(tags) == 0 or len(desc) < 20 or not buw
            if not needs:
                continue

            profiles = await self._skill_memory.get_profiles([slug])
            profile  = profiles.get(slug, {})
            prompt = (
                f"Skill name: {skill.get('name', slug)}\n"
                f"Current description: {desc or '(none)'}\n"
                f"Current tags: {tags or '(none)'}\n"
                f"Real use cases: {profile.get('use_cases', [])[:5] or '(no data)'}\n"
                f"Output fields: {profile.get('output_keys', [])[:10] or '(unknown)'}\n\n"
                f"Write better tags, description, and best_used_when."
            )
            try:
                raw  = await self._llm.complete(prompt, system_prompt=_IMPROVE_SYSTEM)
                raw  = _strip_fences(raw)
                meta = json.loads(raw)
            except Exception as exc:
                log.warning("SkillFactoryBrain: metadata generation failed",
                            extra={"slug": slug, "e": str(exc)})
                continue

            updates: Dict[str, Any] = {}
            if meta.get("tags") and len(meta["tags"]) > len(tags):
                updates["tags"] = meta["tags"]
            if meta.get("description") and len(meta["description"]) > len(desc):
                updates["description"] = meta["description"]
            if meta.get("best_used_when") and not buw:
                updates["best_used_when"] = meta["best_used_when"]

            if not updates:
                self._improved.add(slug)
                continue

            ok2, resp = await self._patch("/api/skills/improve", {
                "slug":    slug,
                "updates": updates,
                "reason":  f"SkillFactoryBrain: {len(profile.get('use_cases', []))} real use cases",
            })
            if ok2:
                self._improved.add(slug)
                improved += 1
            await asyncio.sleep(1)

        if improved:
            log.info("SkillFactoryBrain: improvement cycle done", extra={"improved": improved})

    # ── HTTP helpers ──────────────────────────────────────────────────────────

    def _headers(self) -> Dict[str, str]:
        return {"X-Giga-Secret": self._secret, "Content-Type": "application/json"}

    async def _get(self, path: str) -> Tuple[bool, dict]:
        try:
            async with aiohttp.ClientSession() as s:
                async with s.get(
                    f"{self._gateway_url}{path}",
                    headers=self._headers(),
                    timeout=aiohttp.ClientTimeout(total=_HTTP_TIMEOUT_S),
                ) as r:
                    data = await r.json()
                    return r.status < 300, data
        except Exception as exc:
            log.error("SkillFactoryBrain: GET failed", extra={"path": path, "e": str(exc)})
            return False, {}

    async def _post(self, path: str, body: dict) -> Tuple[bool, dict]:
        try:
            async with aiohttp.ClientSession() as s:
                async with s.post(
                    f"{self._gateway_url}{path}",
                    json=body,
                    headers=self._headers(),
                    timeout=aiohttp.ClientTimeout(total=_HTTP_TIMEOUT_S),
                ) as r:
                    data = await r.json()
                    return r.status < 300, data
        except Exception as exc:
            log.error("SkillFactoryBrain: POST failed", extra={"path": path, "e": str(exc)})
            return False, {}

    async def _patch(self, path: str, body: dict) -> Tuple[bool, dict]:
        try:
            async with aiohttp.ClientSession() as s:
                async with s.patch(
                    f"{self._gateway_url}{path}",
                    json=body,
                    headers=self._headers(),
                    timeout=aiohttp.ClientTimeout(total=_HTTP_TIMEOUT_S),
                ) as r:
                    data = await r.json()
                    return r.status < 300, data
        except Exception as exc:
            log.error("SkillFactoryBrain: PATCH failed", extra={"path": path, "e": str(exc)})
            return False, {}


def _strip_fences(s: str) -> str:
    s = s.strip()
    if s.startswith("```"):
        s = s.split("\n", 1)[1].rsplit("```", 1)[0].strip()
    return s
